[workspace]
members = ["fht-compositor", "smithay-egui"]
resolver = "2"

[workspace.dependencies]
egui = "0.23"
egui_glow = "0.23"
egui_extras = "0.23"
profiling = "1.0.14"

[workspace.dependencies.smithay]
# git = "https://github.com/Smithay/Smithay"
# rev = "7f9e6d5"
git = "https://github.com/cmeissl/smithay"
branch = "perf/reduce_mem_allocations"
default-features = false

[workspace.dependencies.smithay-drm-extras]
# git = "https://github.com/smithay/smithay"
# rev = "7f9e6d5"
git = "https://github.com/cmeissl/smithay"
branch = "perf/reduce_mem_allocations"

[build]
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
    "-Z", "threads=8"
]

# [profile.release]
# codegen-units = 1
# lto = "fat"

[profile.dev]
opt-level = 3
