[workspace]
members = ["fht-compositor", "fht-share-picker", "smithay-egui"]
resolver = "2"

[workspace.dependencies]
egui = "0.23"
egui_glow = "0.23"
egui_extras = "0.23"
profiling = "1.0.14"
serde = { version = "1.0.196", features = ["derive"] }
zbus = "4.1.2"
zvariant = { version = "4.0.0", features = ["option-as-array"] }

[workspace.dependencies.smithay]
git = "https://github.com/Smithay/Smithay"
rev = "e5f0068"
default-features = false

[workspace.dependencies.smithay-drm-extras]
git = "https://github.com/Smithay/Smithay"
rev = "e5f0068"

[build]
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
    "-Z", "threads=8"
]

[profile.opt]
inherits = "release"
codegen-units = 1
lto = "fat"
opt-level = 3

[profile.dev]
opt-level = 3
