[package]
name = "fht-config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xdg.workspace = true
ron.workspace = true
serde.workspace = true
thiserror = "1.0.56"
